services:
  app:
    container_name: app
    build: .
    restart: always
    depends_on:
      - db
    environment:
      APP_PORT: ${APP_PORT}
      APP_HOST: ${APP_HOST}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USER: ${DB_USER}
    ports:
      - ${APP_PORT}:${APP_PORT}

  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
